updates to documentation and insertion of cookbooks
chronicleworks/chronicle pull request #418
Opened 2023-10-23 15:30 UTC by ChrisH1066

# PR Checklist

## Please complete this checklist after opening your PR

* [x] I have updated documentation as necessary
* [x] I have updated helm chart(s) if needed
* [x] I have added tests if needed
* [x] All new and existing tests are passing
* [x] Any breaking changes are clearly flagged and documented
* [x] I’ve included a link to any relevant ticket(s)

2023-10-23 15:55 UTC, mtbc commented
#416 should fix the `cargo-checkmate` issues. The DCO failure is that you need the `Signed-off-by:` bit in your commit message.

2023-11-15 07:53 UTC, duncanjw requested changes
Installing with Sextant should be replaced with Installing with Rancher and either the cookbook stuff pulled into here or at the very least referenced. I prefer the former. Either way we will need to get SUSE to update any cookbook links etc

2023-11-15 07:53 UTC, duncanjw commented on docs/assets/logos/favicon.png
Presumably we should change this and use the Chronicle marque

2023-11-20 16:15 UTC, ryan-s-roberts approved these changes

2023-11-20 16:27 UTC, merged